import { Champ } from "../interfaces/champ";
import { Region , Element, Weapon, Sex} from "../interfaces/data";

export const champions: Champ[] = [
    {id: 1, name: 'Albedo', region: Region.M, element: Element.G, weapon: Weapon.S, gender: Sex.M},
    {id: 2, name: 'Alhaitham', region: Region.S, element: Element.D, weapon: Weapon.S, gender: Sex.M},
    {id: 3, name: 'Aloy', region: Region.O, element: Element.C, weapon: Weapon.B, gender: Sex.F},
    {id: 4, name: 'Amber', region: Region.M, element: Element.P, weapon: Weapon.B, gender: Sex.F},
    {id: 5, name: 'Arataki Itto', region: Region.I, element: Element.G, weapon: Weapon.C, gender: Sex.M},
    {id: 6, name: 'Aether', region: Region.O, element: Element.O, weapon: Weapon.S, gender: Sex.M},
    {id: 7, name: 'Baizhu', region: Region.L, element: Element.D, weapon: Weapon.K, gender: Sex.M},
    {id: 8, name: 'Barbara', region: Region.M, element: Element.H, weapon: Weapon.K, gender: Sex.F},
    {id: 9, name: 'Beidou', region: Region.L, element: Element.E, weapon: Weapon.C, gender: Sex.F},
    {id: 10, name: 'Bennett', region: Region.M, element: Element.P, weapon: Weapon.S, gender: Sex.M},
    {id: 11, name: 'Candace', region: Region.S, element: Element.H, weapon: Weapon.P, gender: Sex.F},
    {id: 12, name: 'Chongyun', region: Region.L, element: Element.C, weapon: Weapon.C, gender: Sex.M},
    {id: 13, name: 'Clorinde', region: Region.F, element: Element.E, weapon: Weapon.S, gender: Sex.F},
    {id: 14, name: 'Collei', region: Region.S, element: Element.D, weapon: Weapon.B, gender: Sex.F},
    {id: 15, name: 'Dehya', region: Region.S, element: Element.P, weapon: Weapon.C, gender: Sex.F},
    {id: 16, name: 'Diluc', region: Region.M, element: Element.P, weapon: Weapon.C, gender: Sex.M},
    {id: 17, name: 'Diona', region: Region.M, element: Element.C, weapon: Weapon.B, gender: Sex.F},
    {id: 18, name: 'Dori', region: Region.S, element: Element.E, weapon: Weapon.C, gender: Sex.F},
    {id: 19, name: 'Eula', region: Region.M, element: Element.C, weapon: Weapon.C, gender: Sex.F},
    {id: 20, name: 'Faruzan', region: Region.S, element: Element.A, weapon: Weapon.B, gender: Sex.F},
    {id: 21, name: 'Fischl', region: Region.M, element: Element.E, weapon: Weapon.B, gender: Sex.F},
    {id: 22, name: 'Freminet', region: Region.F, element: Element.C, weapon: Weapon.C, gender: Sex.M},
    {id: 23, name: 'Ganyu', region: Region.L, element: Element.C, weapon: Weapon.B, gender: Sex.F},
    {id: 24, name: 'Gorou', region: Region.I, element: Element.G, weapon: Weapon.B, gender: Sex.M},
    {id: 25, name: 'Heizou', region: Region.I, element: Element.A, weapon: Weapon.K, gender: Sex.M},
    {id: 26, name: 'Hu Tao', region: Region.L, element: Element.P, weapon: Weapon.P, gender: Sex.F},
    {id: 27, name: 'Jean', region: Region.M, element: Element.A, weapon: Weapon.S, gender: Sex.F},
    {id: 28, name: 'Kaedehara Kazuha', region: Region.I, element: Element.A, weapon: Weapon.S, gender: Sex.M},
    {id: 29, name: 'Kaeya', region: Region.M, element: Element.C, weapon: Weapon.S, gender: Sex.M},
    {id: 30, name: 'Kamisato Ayaka', region: Region.I, element: Element.C, weapon: Weapon.S, gender: Sex.F},
    {id: 31, name: 'Kamisato Ayato', region: Region.I, element: Element.H, weapon: Weapon.S, gender: Sex.M},
    {id: 32, name: 'Kaveh', region: Region.S, element: Element.D, weapon: Weapon.C, gender: Sex.M},
    {id: 33, name: 'Keqing', region: Region.L, element: Element.E, weapon: Weapon.S, gender: Sex.F},
    {id: 34, name: 'Kirara', region: Region.I, element: Element.D, weapon: Weapon.S, gender: Sex.F},
    {id: 35, name: 'Klee', region: Region.M, element: Element.P, weapon: Weapon.K, gender: Sex.F},
    {id: 36, name: 'Kuki Shinobu', region: Region.I, element: Element.E, weapon: Weapon.S, gender: Sex.F},
    {id: 37, name: 'Layla', region: Region.S, element: Element.C, weapon: Weapon.S, gender: Sex.F},
    {id: 38, name: 'Lisa', region: Region.M, element: Element.E, weapon: Weapon.K, gender: Sex.F},
    {id: 39, name: 'Lumine', region: Region.O, element: Element.O, weapon: Weapon.S, gender: Sex.F},
    {id: 40, name: 'Lynette', region: Region.F, element: Element.A, weapon: Weapon.S, gender: Sex.F},
    {id: 41, name: 'Lyney', region: Region.F, element: Element.P, weapon: Weapon.B, gender: Sex.M},
    {id: 42, name: 'Mika', region: Region.M, element: Element.C, weapon: Weapon.P, gender: Sex.M},
    {id: 43, name: 'Mona', region: Region.M, element: Element.H, weapon: Weapon.K, gender: Sex.F},
    {id: 44, name: 'Nahida', region: Region.S, element: Element.D, weapon: Weapon.K, gender: Sex.F},
    {id: 45, name: 'Navia', region: Region.F, element: Element.G, weapon: Weapon.C, gender: Sex.F},
    {id: 46, name: 'Neuvillette', region: Region.F, element: Element.H, weapon: Weapon.K, gender: Sex.M},
    {id: 47, name: 'Nilou', region: Region.S, element: Element.H, weapon: Weapon.S, gender: Sex.F},
    {id: 48, name: 'Ningguang', region: Region.L, element: Element.G, weapon: Weapon.K, gender: Sex.F},
    {id: 49, name: 'Noelle', region: Region.M, element: Element.G, weapon: Weapon.C, gender: Sex.F},
    {id: 50, name: 'Qiqi', region: Region.L, element: Element.C, weapon: Weapon.S, gender: Sex.F},
    {id: 51, name: 'Raiden Shogun', region: Region.I, element: Element.E, weapon: Weapon.P, gender: Sex.F},
    {id: 52, name: 'Razor', region: Region.M, element: Element.E, weapon: Weapon.C, gender: Sex.M},
    {id: 53, name: 'Rosaria', region: Region.M, element: Element.C, weapon: Weapon.P, gender: Sex.F},
    {id: 54, name: 'Sangonomiya Kokomi', region: Region.I, element: Element.H, weapon: Weapon.K, gender: Sex.F},
    {id: 55, name: 'Sayu', region: Region.I, element: Element.A, weapon: Weapon.C, gender: Sex.F},
    {id: 56, name: 'Shenhe', region: Region.L, element: Element.C, weapon: Weapon.P, gender: Sex.F},
    {id: 57, name: 'Sucrose', region: Region.M, element: Element.A, weapon: Weapon.K, gender: Sex.F},
    {id: 58, name: 'Tartaglia (Childe)', region: Region.Sh, element: Element.H, weapon: Weapon.B, gender: Sex.M},
    {id: 59, name: 'Thoma', region: Region.M, element: Element.P, weapon: Weapon.P, gender: Sex.M},
    {id: 60, name: 'Tighnari', region: Region.S, element: Element.D, weapon: Weapon.B, gender: Sex.M},
    {id: 61, name: 'Venti', region: Region.M, element: Element.A, weapon: Weapon.B, gender: Sex.M},
    {id: 62, name: 'Wanderer', region: Region.I, element: Element.A, weapon: Weapon.K, gender: Sex.M},
    {id: 63, name: 'Wriothesley', region: Region.F, element: Element.C, weapon: Weapon.K, gender: Sex.M},
    {id: 64, name: 'Xiangling', region: Region.L, element: Element.P, weapon: Weapon.P, gender: Sex.F},
    {id: 65, name: 'Xiao', region: Region.L, element: Element.A, weapon: Weapon.P, gender: Sex.M},
    {id: 66, name: 'Xingqiu', region: Region.L, element: Element.H, weapon: Weapon.S, gender: Sex.M},
    {id: 67, name: 'Xinyan', region: Region.L, element: Element.P, weapon: Weapon.C, gender: Sex.F},
    {id: 68, name: 'Yanfei', region: Region.L, element: Element.P, weapon: Weapon.K, gender: Sex.F},
    {id: 69, name: 'Yaoyao', region: Region.L, element: Element.D, weapon: Weapon.P, gender: Sex.F},
    {id: 70, name: 'Yae Miko', region: Region.I, element: Element.E, weapon: Weapon.K, gender: Sex.F},
    {id: 71, name: 'Yoimiya', region: Region.I, element: Element.P, weapon: Weapon.B, gender: Sex.F},
    {id: 72, name: 'Yun Jin', region: Region.L, element: Element.G, weapon: Weapon.P, gender: Sex.F},
    {id: 73, name: 'Zhongli', region: Region.L, element: Element.G, weapon: Weapon.P, gender: Sex.M}
];